# Generated by Django 5.0.3 on 2024-03-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("html", "HTML"),
                            ("css", "CSS"),
                            ("java", "Java"),
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("csharp", "C#"),
                            ("php", "PHP"),
                            ("ruby", "Ruby"),
                            ("perl", "Perl"),
                            ("bash", "Bash"),
                            ("powershell", "PowerShell"),
                            ("sql", "SQL"),
                            ("plaintext", "Plain Text"),
                        ],
                        max_length=100,
                    ),
                ),
                ("code", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
